algo = input('Digite algo: ')
print('O tipo primitivo é: ', type (algo))
print(f'É capitalizada ? {algo.istitle()}')
print(f'É minuscula ? {algo.islower()}')
print(f'É maiscula ? {algo.isupper()}')
print('É numerica ?', algo.isnumeric())
print('É letra ?', algo.isalpha())
print('É alfanumerica ?', algo.isalnum())
print('É espaço ?', algo.isspace())
